// Generated by CoffeeScript 1.7.1

/*
jquery-future v.0.0.1
 */

(function() {
  var enchanced, futuredMethod, methodize, methods,
    __slice = [].slice;

  window.future = window.future || {};

  future.map = function(prom, fn) {
    var d;
    d = $.Deferred();
    prom.then(function() {
      var results;
      results = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return d.resolve(fn.apply(null, results));
    }, function() {
      var results;
      results = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return d.reject(fn.apply(null, results));
    });
    return Future(d.promise());
  };

  future.flatMap = function(promise, fn) {
    var deferred, reject;
    deferred = $.Deferred();
    reject = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return deferred.reject.apply(deferred, args);
    };
    promise.then(function() {
      var results, secondPromise;
      results = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      secondPromise = fn.apply(null, results);
      return secondPromise.then(function() {
        var otherResults;
        otherResults = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return deferred.resolve.apply(deferred, otherResults);
      }, reject);
    }, reject);
    return deferred.promise();
  };

  future.select = function(promiseArray) {
    var d, promise, resolve, _i, _len;
    d = $.Deferred();
    resolve = function(promise, promiseResult) {
      var otherPromises, p;
      otherPromises = ((function() {
        var _i, _len, _results;
        if (p !== promise) {
          _results = [];
          for (_i = 0, _len = promiseArray.length; _i < _len; _i++) {
            p = promiseArray[_i];
            _results.push(p);
          }
          return _results;
        }
      })());
      return d.resolve(promiseResult, otherPromises);
    };
    for (_i = 0, _len = promiseArray.length; _i < _len; _i++) {
      promise = promiseArray[_i];
      promise.done(_.partial(resolve, promise));
    }
    return d.promise();
  };

  future.join = function() {
    var promises;
    promises = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.when.apply($, promises).promise();
  };

  future.collect = function(promiseArray) {
    return $.when.apply($, promiseArray).promise();
  };

  future.rescue = function(prom, fn) {
    var deferred;
    deferred = $.Deferred();
    prom.fail(function() {
      var args, newPromise;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      newPromise = fn.apply(null, args);
      return newPromise.then(function() {
        var newResults;
        newResults = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return deferred.resolve.apply(deferred, newResults);
      });
    });
    return deferred.promise();
  };

  future.handle = function(prom, fn) {
    var deferred;
    deferred = $.Deferred();
    prom.fail(function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return deferred.reject(fn.apply(null, args));
    });
    return deferred.promise();
  };

  methodize = function(obj, funcName) {
    return function(fn) {
      return $[funcName](obj, fn);
    };
  };

  futuredMethod = function(obj, funcName) {
    return _.compose(obj[funcName], Future);
  };

  methods = ['mapProm', 'flatMap', 'handle', 'rescue'];

  enchanced = ['done'];

  window.Future = function(obj) {
    var f, funcName, _i, _j, _len, _len1;
    for (_i = 0, _len = methods.length; _i < _len; _i++) {
      funcName = methods[_i];
      obj[funcName] = methodize(obj, funcName);
    }
    for (_j = 0, _len1 = enchanced.length; _j < _len1; _j++) {
      f = enchanced[_j];
      obj[f] = futuredMethod(obj, f);
    }
    return obj;
  };

}).call(this);
